### ISSUE TITLE
UnknownApiNameOrVersion( googleapiclient.errors.UnknownApiNameOrVersion: name: drive version: v2

### ISSUE THREAD

**Issue by Legend-Recalls** [codegallivant/gdrive-interact-python#1]
As the title suggests

**Comment by codegallivant** [comment]
@Legend-Recalls  This error doesn't appear for me whenever I use the script. Could you please specify how to reproduce the error? A few sites mentioned it appearing after converting the .py file to .exe while using a certain pip module. Was that the case here?

**Comment by codegallivant** [comment]
@Legend-Recalls I just tested the program again and am not getting any such error. Please at least specify the line number which returns the corresponding error. Since this issue has been inactive for quite some time and you seem to have moved on, I am closing it for now.
